### ISSUE TITLE
Probability limit

### ISSUE THREAD

**Issue by jonhelium** [jmbejara/comp-econ-sp19#20]
Hello,

I'm a bit confused about the use of the term "probability limit" in question Q3 of the Monte Carlo IV assignment: the question asks us to derive the expression for the bias of the estimate of 𝛽1-hat in the probability limit, but I was under the impression that the probability limit of 𝛽1-hat is more of a concern when considering the consistency of an OLS estimator. Is this not the case?

**Comment by jmbejara** [comment]
Hi @jonhelium . Looking back at this, I would probably reword it. I am really just looking for an expression for the bias of the estimate "in population terms." The way that I conceive this, it should be the same thing as taking the bias of the estimator and considering its value in the probability limit. I'm just looking for a theoretical derivation of the bias under the assumption that you had infinite draws of the data. 

Since x_1 is correlated with the error term, an OLS estimate of it is neither unbiased or consistent.
