### ISSUE TITLE
Handling data that is "Missing or ___"

### ISSUE THREAD

**Issue by IshaanW** [jmbejara/comp-econ-sp19#33]
I'm working through the guided cleaning of the IPUMS CPS dataset and am removing missing/NIU values. For the variable 'EDUC', the documentation has the following codings:

002: None or preschool
000: NIU or no schooling

How should we treat codes like these that might be coded as Nan but may also be indicating real values?

**Comment by jmbejara** [comment]
Good question. It looks like `000:NUI or no schooling` isn't available for the ASEC samples anyway. 

![image](https://user-images.githubusercontent.com/3770323/57098228-41441b00-6cdf-11e9-904a-fa59cecc779b.png)

The code `002: None or preschool` should be left in because it indicates whether the person has no formal education or only at least preschool. (At least that's how I read it.)
