### ISSUE TITLE
hw 4, q12

### ISSUE THREAD

**Issue by cangubur** [jmbejara/comp-econ-sp19#37]
I do this to calculate ave_wage in part 11

<img width="971" alt="Screen Shot 2019-05-04 at 3 31 27 PM" src="https://user-images.githubusercontent.com/49253053/57184485-dc74f600-6e81-11e9-8f7c-5ac75a147db9.png">

However, when I do concat in part 12 my results are slightly different than yours. Do you see a reason for the difference?

<img width="168" alt="Screen Shot 2019-05-04 at 3 31 45 PM" src="https://user-images.githubusercontent.com/49253053/57184494-f44c7a00-6e81-11e9-92e4-ac077f727287.png">

**Comment by richard-archer** [comment]
Another question in the same vein - the only thing that I see that should be changed between median_wages and ave_wages is changing weightedstats.weighted_median to weightedstats.weighted_mean - but this change prevents the code for ave_wages from running. Is there some additional change that needs to be made that I'm missing?

**Comment by jmbejara** [comment]
@cangubur Your code is the same as mine here. I don't see any reason for a difference. It's minor enough that it shouldn't matter. I recall a lot of minor differences coming up last year because of things like differences in the order in which people dropped missing data (difference subsets of columns result in different drop criteria). I just noticed that in my code, I drop rows at a point before I drop unnecessary columns. This changes my results slightly, but they still aren't exactly like yours. I'm going to upload my new screenshots soon.

I'll make sure to ask @ariboyarsky to give full credit as long as the answers are in the right ballpark (as they are here).
