### ISSUE TITLE
Installed scikit-misc but cannot be found

### ISSUE THREAD

**Issue by jonhelium** [jmbejara/comp-econ-sp19#45]
Whenever I try to use 'method = loess' within geom_smooth() I receive the error "For loess smoothing, install 'scikit-misc'", but I already used the terminal to install 'scikit-misc' via 'pip install scikit-misc'. Is there something I'm missing such that 'loess' doesn't run?

**Comment by jmbejara** [comment]
That's strange. Try restarting jupyter completely. I can't say for sure. Maybe you could share the terminal output you get after you install 'scikit-misc'. We could try some other things after that

**Comment by jonhelium** [comment]
I tried restarting Jupyter and the kernel but the same error keeps appearing. Here is a screenshot of my terminal output after trying install 'scikit-misc' again:

![pip scikit-misc](https://user-images.githubusercontent.com/28125099/57575825-d8b01900-7417-11e9-93c2-603fdc7c32ca.jpg)

**Comment by jmbejara** [comment]
Hmm. You might have an issue of having multiple installations of python. Try running the following commands in the command line: `which pip` and `which python`. Do this in the regular command prompt and the anaconda command prompt. Copy and paste the results for each.

**Comment by jonhelium** [comment]
I've tried using `which pip` and `which python` in both the regular command prompt and Anaconda command prompt but neither seem to recognize `which `as a command.
![which_error](https://user-images.githubusercontent.com/28125099/57577505-1e7fd800-743e-11e9-9eb3-a3ca93d87723.jpg)

**Comment by jmbejara** [comment]
Could you try the same thing with `where` ? If that doesn't work, it might be best to try to work through the issue in Ari's office hours tomorrow.

**Comment by jonhelium** [comment]
I tried using `where` and it does tell me where my installation of `pip` and `python` are... I don't think this indicates that I have multiple installs of Python but I wouldn't sure of that.
![where_pip_python](https://user-images.githubusercontent.com/28125099/57588557-9e0fb480-74db-11e9-9ed5-fd527d67d535.jpg)

**Comment by jmbejara** [comment]
I'm assuming that you installed Anaconda and are using Anaconda. The path that is returned is not the default path for an Anaconda installation. It looks like you have a second installation of Python on your computer. (https://xkcd.com/1987/  :) ) Try these things:

 - run `pip install scikit-misc' in the Anaconda prompt. See if that fixes things.
 - If that doesn't work, try opening control panel and go to "add or remove programs". Look for a non-Anaconda version of Python 3.7 and uninstall it. Then try the previous step again.

**Comment by jonhelium** [comment]
I've tried the above after uninstalling a non-Anaconda version of Python but it doesn't seem like anything was resolved - there is now another more urgent issue of a Kernel error I am now receiving in every jupyter notebook: "FileNotFoundError: [WinError 2] The system cannot find the file specified" :(

Do I have to re-install Python again?
Edit: Or could this possibly be an error with my PATH variables?

**Comment by jmbejara** [comment]
Oh no! Sorry this is such a pain. Ok. It seems like the issue is that Jupyter notebook has been configured to run with a different Python installation than the one that was installed by Anaconda. You need to change the settings to let Jupyter know to use the Anaconda one. Try this.

 - Make sure all other command prompt are closed. Make sure Jupyter and all anaconda apps are closed. 
 - Open the anaconda prompt (it's important to use the Anaconda prompt)
 - Run this command: `python -m ipykernel install --user`
 - Then type `jupyter notebook`
 - Try running your file again and see if that fixed the issue.
 - If it didn't work, run this in an Anaconda prompt: `jupyter kernelspec list`
 - Open File Explorer and delete the file that is returned by the command `jupyter kernelspec list`
 - Try again to see if this fixed the problem. If not, uninstall Anaconda. Uninstall all Python programs you can find. Install Anaconda from scratch.


Here are my references:

 - https://github.com/jupyter/notebook/issues/4079
 - https://github.com/jupyter/notebook/issues/2301

**Comment by jonhelium** [comment]
Hooray!!! I followed the 1st four bullet points from above and now everything is working fine (including calling `scikit-misc`)! Thanks so much for helping out so much with these issues, really appreciate! :)
