### ISSUE TITLE
MLE Q6 negative std

### ISSUE THREAD

**Issue by sicelyli** [jmbejara/comp-econ-sp19#46]
I got a negative std estimation(-0.03892627616515054), but not sure what goes wrong with my code:
![Screen Shot 2019-05-12 at 7 31 26 PM](https://user-images.githubusercontent.com/49537572/57589824-a45a5c80-74ec-11e9-9cfd-73191e915926.png)

**Comment by jmbejara** [comment]
Try rewriting your PDF so that sigma appears as sigma**2 or the absolute value of sigma. You can do this without changing the PDF. An alternative is to add a constraint to the optimizer to force sigma to be positive. However, this can introduce some numerical issues that make the first option easier and more reliable.
