### ISSUE TITLE
Variable Length of Theta depending on N

### ISSUE THREAD

**Issue by IshaanW** [jmbejara/comp-econ-sp19#50]
In the first question when we are supposed to calculate log-likelihood, you write that the function we write should use fixed lengths of n=6 for both alpha and gamma but aren't the lengths of these vectors dependent on the number of firms? Is it implied that we treat all observations with 5 or more firms the same?

**Comment by jmbejara** [comment]
Hi. Good questions. These are parameters to be estimated from the whole sample, not for individual markets. It's just like in OLS when you have binary variables as explanatory variables and you're estimating coefficients.

And, as a separate question, we have designed the fixed cost function so that the fixed costs don't change after the 5th entrant. So, all markets with 5 or more entrants are treated the same in this regard.
