### ISSUE TITLE
Optimizer not working but generating correct log-likelihood values

### ISSUE THREAD

**Issue by IshaanW** [jmbejara/comp-econ-sp19#61]
My negative log-likelihood function is outputting the correct value for Q1 and when I input the correct theta, produces a value of 276.52 which is fairly close to the reported value in the paper of 263.09. However, my optimizer results are alternating between the initial guess theta0 and being completely incorrect. I'm not sure how to proceed with debugging. [I've added bounds for alphas which I believe are working correctly]

**Comment by jmbejara** [comment]
Your result is close, but there difference seems large enough that I would not be confident proceeding. I'm continue with Q1.

Also, note that the optimizer should take at least a few minutes to run. You can also test the optimizer by putting in a different initial value. For example, you can input the correct answer as the initial value and see if the optimizer succeeds at staying at the correct answer. We happen to know what the correct answer is because it's in the paper.
